package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	db "github.com/brkss/gogql/db/sqlc"
	"github.com/brkss/gogql/graph/model"
	"github.com/brkss/gogql/middleware"
	"github.com/brkss/gogql/utils"
	"github.com/google/uuid"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginUserInput) (*model.AuthResponse, error) {
	user, err := r.Store.GetUserByEmail(ctx, input.Email)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Something went wrong !",
		}
	}
	err = utils.VerifyPassword(user.Password, input.Password)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Invalid Password !",
		}
	}

	token, accessPayload, err := r.Maker.CreateToken(user.ID, r.Config.TokenDuration)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Cannot create token !",
		}
	}

	refreshToken, refreshPayload, err := r.Maker.CreateToken(user.ID, r.Config.RefreshTokenDuration)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Cannot create refresh token !",
		}
	}

	// create session !
	_, err = r.Store.CreateSession(ctx, db.CreateSessionParams{
		ID:        refreshPayload.ID,
		UserID:    user.ID,
		Token:     refreshToken,
		ExpiredAt: refreshPayload.ExpireAt,
		Blocked:   false,
	})
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "cannot create refresh token !",
		}
	}

	ac_exp := accessPayload.ExpireAt.String()
	rf_exp := refreshPayload.ExpireAt.String()

	return &model.AuthResponse{
		Status:                false,
		AccessToken:           &token,
		RefreshToken:          &refreshToken,
		RefreshTokenExpiresAt: &rf_exp,
		AccessTokenExpiresAt:  &ac_exp,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input *model.RegisterUserInput) (*model.AuthResponse, error) {
	hashedPassword, err := utils.HashPassword(input.Password)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Cannot hasdh password !",
		}
	}
	arg := db.CreateUserParams{
		ID:       uuid.New().String(),
		Name:     input.Name,
		Email:    input.Email,
		Password: hashedPassword,
		Age: int32(input.Age),
	}
	user, err := r.Store.CreateUser(ctx, arg)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "cannot create user ! : " + err.Error(),
		}
	}

	token, accessPayload, err := r.Maker.CreateToken(user.ID, r.Config.TokenDuration)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Cannot create token !",
		}
	}

	refreshToken, refreshPayload, err := r.Maker.CreateToken(user.ID, r.Config.RefreshTokenDuration)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Cannot create refresh token !",
		}
	}

	// create session !
	_, err = r.Store.CreateSession(ctx, db.CreateSessionParams{
		ID:        refreshPayload.ID,
		UserID:    user.ID,
		Token:     refreshToken,
		ExpiredAt: refreshPayload.ExpireAt,
		Blocked:   false,
	})
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "cannot create refresh token !",
		}
	}

	ac_exp := accessPayload.ExpireAt.String()
	rf_exp := refreshPayload.ExpireAt.String()

	return &model.AuthResponse{
		Status:                false,
		AccessToken:           &token,
		RefreshToken:          &refreshToken,
		RefreshTokenExpiresAt: &rf_exp,
		AccessTokenExpiresAt:  &ac_exp,
	}, nil
}

// Me is the resolver for the Me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	payload := middleware.GetPayload(ctx)
	if payload == nil {
		return nil, &gqlerror.Error{
			Message: "Access Denied",
		}
	}
	user, err := r.Store.GetUser(ctx, payload.UserID)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: "Something went wrong !",
		}
	}

	response := model.User{
		ID:    user.ID,
		Name:  user.Name,
		Email: user.Email,
	}

	return &response, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
