DROP TABLE IF EXISTS surveyed;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS surveys;
DROP TABLE IF EXISTS exercices;
DROP TABLE IF EXISTS users;

