// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         string `json:"id"`
	Ans        string `json:"ans"`
	QuestionID string `json:"question_id"`
	Val        int32  `json:"val"`
}

type Awarness struct {
	ID             string         `json:"id"`
	Content        string         `json:"content"`
	Image          string         `json:"image"`
	SurveyID       sql.NullString `json:"survey_id"`
	Title          string         `json:"title"`
	GradientTop    string         `json:"gradient_top"`
	GradientBottom string         `json:"gradient_bottom"`
}

type Exercice struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Duration  string    `json:"duration"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Question struct {
	ID       string `json:"id"`
	Qst      string `json:"qst"`
	SurveyID string `json:"survey_id"`
}

type Result struct {
	ID       string `json:"id"`
	Min      int32  `json:"min"`
	Max      int32  `json:"max"`
	Comment  string `json:"comment"`
	SurverID string `json:"surver_id"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Token     string    `json:"token"`
	Blocked   bool      `json:"blocked"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Survey struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Surveyed struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	SurveyID   string `json:"survey_id"`
	QuestionID string `json:"question_id"`
	AnswerID   string `json:"answer_id"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	Age       int32     `json:"age"`
}

type Verfication struct {
	ID        string    `json:"id"`
	Code      string    `json:"code"`
	UserID    string    `json:"user_id"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
	Blocked   bool      `json:"blocked"`
}
