// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Answer struct {
	ID         string `json:"id"`
	Ans        string `json:"ans"`
	QuestionID string `json:"question_id"`
}

type Exercice struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Duration  string    `json:"duration"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Question struct {
	ID       string `json:"id"`
	Qst      string `json:"qst"`
	SurveyID string `json:"survey_id"`
}

type Result struct {
	ID       string `json:"id"`
	Min      int32  `json:"min"`
	Max      int32  `json:"max"`
	Comment  string `json:"comment"`
	SurverID string `json:"surver_id"`
}

type Survey struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Surveyed struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	SurveyID   string `json:"survey_id"`
	QuestionID string `json:"question_id"`
	AnswerID   string `json:"answer_id"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Age       int32     `json:"age"`
	CreatedAt time.Time `json:"created_at"`
}
